### PR TITLE
Remove all the rails nonsense and cyclic dependency

### PR DESCRIPTION
**Pull request by maximebedard**
Given that we do not use any of this, I'm rm -rf it all of it.

This will remove a weird cyclic dependency, and stop generating all the _orig methods and polluting the memcached client with a whole bunch of useless commands. 

Any thoughts?

### CODE REVIEW

**Comment by tylermercier** [comment]
What are you worried about this breaking? It seems fine to me that we could delete this code and verify things work correctly in core.

**Comment by maximebedard** [comment]
This won't break anything. My main worry is diverging even more from the upstream, but we are already far gone, so I don't think it's a big deal.

**Review by tylermercier — APPROVED** [review]

**Comment by dylanahsmith** [comment]
> My main worry is diverging even more from the upstream, but we are already far gone, so I don't think it's a big deal.

I don't understand why you say we were so far gone from upstream.  Before this PR, https://github.com/Shopify/memcached/pull/1 was the only PR not in upstream.

**Comment by maximebedard** [comment]
Yes, but we are already pinned to 1.8 I think, whereas upstream master is 250 commits ahead and completely different from what we are using.

**Comment by dylanahsmith** [comment]
1.8 is the latest release.  There is a 1-0-stable branch which we could contribute more minor changes and the master branch that I think has already Memcached::Rails as well as being in the process of replacing swig with a hand written C extension wrapping libmemcached.

**Pull request merged**
