### PR TITLE
Accept unix:// servers

### PR DESCRIPTION
**Pull request by casperisfine**
Since the init code check for `File.socket?` for unix paths if the server isn't yet ready the client raise which cause an depedency on the server.

To avoid that we can accept `unix://` URLs, and remove the prefix.

When it there, we can bypass the `File.socket?` check.

### CODE REVIEW

**Review by DazWorrall — APPROVED** [review]
This change LGTM.

Afaict we don't test the server missing/flapping behaviour with a unix socket based server. Are we sure it will handle unix socket based servers the same as TCP? 

https://github.com/Shopify/memcached/blob/ba4acf10647863ff336ba775666889f84fab176c/test/unit/memcached_test.rb#L1156

**Comment by casperisfine** [comment]
> Are we sure it will handle unix socket based servers the same as TCP?

I'm not 100% sure, but it's done by libmemcached, so I'd assume it does?

**Comment by DazWorrall** [comment]
> it's done by libmemcached

Ok, happy for that stuff to be delegated there 👍

**Comment by casperisfine** [comment]
> so I'd assume it does?

By that I mean, I checked the code to see if it was fine to add a UNIX server that isn't yet up, and all the codepath where the same except for some occasional `if (prococol == UDP)` checks. So I assume all the circuit breaker part is the same.

**Pull request merged**
