### PR TITLE
Add server death logging

### PR DESCRIPTION
**Pull request by fbogsany**
This adds logging to `memcached_connect` to report the server marked dead and the live server count when returning `MEMCACHED_SERVER_MARKED_DEAD`.

@camilo for review

### CODE REVIEW

**Comment by camilo** [comment]
@fbogsany this never got merged?! I think we are runnin this in prod

**Comment by fw42** [comment]
yeah we are running it off this branch via the git ref

**Comment by camilo** [comment]
hmrr we should not iamma merge and point to head

**Comment by camilo** [comment]
we'll see about removing noise as well but for now at least I want to follow convention and run out of master.

**Pull request merged**
